### PR TITLE
improving the position marker positioning

### PR DESCRIPTION
**Pull request by neerajanand321**
Uses contours for the detection of the position marker.
Prediction without using contours:
git_before

Prediction after using contours:
git_after

### CODE REVIEW

**Comment by hornig** [comment]
Hi @neerajanand-coder , did you test it with photos? Because it did not work for me when using our test photos we did for https://2021.spaceappschallenge.org/challenges/statements/drones-and-satellites-for-urban-development/teams/osmto/project .

it throws this code...

`C:\Users\station\PycharmProjects\gcp-osm>c:\Python39\python.exe main.py -f c:\Users\station\Downloads\gcp-osm-testpics --debug
Hello, starting GCP-OSM...

loading in all files in folder: c:\Users\station\Downloads\gcp-osm-testpics
('https://osm.to/g/0MAe9lSqV', (68, 68)) -> ClassicGroundControlPoint(center_geo_location=GeoLocation(latitude=50.929536670446396, longitude=11.585404872894287, altitude_in_meters=0), map_object=None)
('', None) -> ('', None) -> ('', None) -> ('', None) -> ('', None) -> ('', None) -> ('', None) -> ('', None) -> Traceback (most recent call last):
  File "C:\Users\station\PycharmProjects\gcp-osm\main.py", line 85, in <module>
    main(args.file)
  File "C:\Users\station\PycharmProjects\gcp-osm\main.py", line 65, in main
    found_qr_codes = qr_code_extractor.get_qr_data(file, debug_show_image=args.is_debug)
  File "C:\Users\station\PycharmProjects\gcp-osm\qr_code_extractor.py", line 11, in get_qr_data
    position_marker_coordinates = get_position_marker_coordinates(input_image)
  File "C:\Users\station\PycharmProjects\gcp-osm\qr_code_extractor.py", line 44, in get_position_marker_coordinates
    center_x = int(M["m10"] / M["m00"])
ZeroDivisionError: float division by zero

C:\Users\station\PycharmProjects\gcp-osm>`

can you please check?

**Comment by neerajanand321** [comment]
Hi! I am trying to resolve it and also from where I could get more test photos?

**Comment by hornig** [comment]
hi, if you follow the link i posted you will find a few on the project page and on the team board.

**Comment by hornig** [comment]
@neerajanand-coder , some idea already?

**Pull request closed without merging**
